version: "3.9"
services:
  web:
    image: "${WEB_IMAGE}"
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    # expose:
    # - 8000
    command: sh -c "chmod +x /code/migrate.sh && sh /code/migrate.sh && /code/entrypoint.sh && /code/collectstatic.sh"
    extra_hosts:
      - "postgresql:139.162.132.251"

    volumes:
    - static_volume:/code/staticfiles
  
  # nginx:
  #   build:
  #       context: ./nginx
  #   volumes:
  #     - static_volume:/code/staticfiles
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - web


volumes:
  static_volume:
  # postgres_data:
