version: "3.9"
services:
  web:
    image: "${APP_IMAGE}"
    restart: always
    command: sh -c "chmod +x migrate.sh && sh migrate.sh && sh entrypoint.sh && sh collectstatic.sh "
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "postgresql:139.162.132.251"
    # Verify function in production
    volumes:
    - static_volume:/home/app/web/staticfiles
    container_name: ads-app

volumes:
  static_volume:
