version: "3.9"
services:
  web:
    build:
      context: ./mysite
      dockerfile: Dockerfile
    command: sh -c "chmod +x migrate.sh && sh migrate.sh && sh entrypoint.sh && sh collectstatic.sh "
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    # expose:
    # - 8000

    extra_hosts:
      - "postgresql:139.162.132.251"

# Verify function in production
    volumes:
    - static_volume:/staticfiles
  
  # nginx:
  #   build:
  #       context: ./nginx
  #   volumes:
  #     - static_volume:/code/staticfiles
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - web


volumes:
  static_volume:
  # postgres_data:






# junk code
  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_django
  #     - POSTGRES_PASSWORD=hello_django
  #     - POSTGRES_DB=hello_django_dev
  #   volumes:
  # - static_volume:/code/staticfiles
  # # - ./mysite/:/code
  # # - media_volume:/code/mediafiles
#     command: sh -c "sh collectstatic.sh"
  # chmod +x /mysite/migrate.sh && sh /mysite/migrate.sh && sh /mysite/entrypoint.sh && 